### ISSUE TITLE
Does it support Android?

### ISSUE THREAD

**Issue by SkulaMesterHU** [dwin/hashify#2]
Hi,

I am trying to create a cross-platform mobile app, and the API works great from my iOS device, but from Android I get Network request failed error.

Any idea?

**Comment by dwin** [comment]
Possibly TLS related. 

What version of Android? What kind of device?

**Comment by SkulaMesterHU** [comment]
Hi,

I am not sure why this error happening, it might be because of Thunkable (the platform I am using) as on some device and even from the phone's browser it does work, but on my S8+ from the app I created it doesn't.

See: https://community.thunkable.com/t/web-api-error-on-android-network-request-failed/1331289

Let me know if you have any idea.
