### ISSUE TITLE
API Down for 4 Days

### ISSUE THREAD

**Issue by JSeeger6** [dwin/hashify#9]
Hi,

The API has been down with a near 0% success rate for 4+ days. Please fix this! @dwin

**Comment by avcenal** [comment]
Same here, is there any ETA to fix it @dwin?? Thanks!!

**Comment by avcenal** [comment]
Thanks a lot @dwin! It is working!

**Comment by JSeeger6** [comment]
Yes!! Confirming that it's working for me too :)
